version: '3.8'

services:
  billing-service:
    build:
      context: ./path/to/billing-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - hotel-network

networks:
  hotel-network:

